name: 🐞 Bug
description: Report a bug or unexpected behavior
title: "[BUG] <Your title here>"
labels: ["bug", "needs triage"]
assignees: []
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue?
      description: Please search the existing issues first.
      options:
        - label: I have searched all existing issues
          required: true
  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Environment Information
      description: |
        - OS: macOS 14 / Ubuntu 22.04
        - Node: 20.x
        - npm: 10.x
