name: 🚀 Feature Request
description: Suggest an idea for a new feature or improvement
title: "[Feature]: "
labels: ["feature", "enhancement"]
body:
  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to add and its purpose.
      placeholder: Please describe the business value or use case.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Implementation Ideas / Expected Outcome
      description: (Optional) Any ideas on how this could be implemented or what the final result should look like.
  - type: textarea
    attributes:
      label: Related Documents or Design Links
      description: (Optional) Link to any relevant mockups, designs, or external documents.
  - type: checkboxes
    attributes:
      label: Acceptance Criteria
      description: (Optional) Define what needs to be true for this feature to be considered complete.
      options:
        - label: Security risks have been evaluated
        - label: Compatibility and regression testing ensured
